name: google-server-api
version: "0.4.1.1"
category: "Web"
synopsis: "Google APIs for server to server applications"
description: This library provides a way to use Google API for server to server applications.
license: "MIT"
author: "Kadzuya Okamoto"
copyright: "2018 Kadzuya Okamoto"
maintainer: "arow.okamoto+github@gmail.com"

extra-source-files:
  - README.md

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - DuplicateRecordFields
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - Strict
  - StrictData
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

dependencies:
  - base >= 4.14 && < 4.18
  - HsOpenSSL >= 0.11 && < 0.12
  - RSA >= 2.4 && < 2.5
  - aeson >= 1.5 && < 2.2
  - aeson-casing >= 0.2 && < 0.3
  - base64-bytestring >= 1.1 && < 1.3
  - bytestring >= 0.10 && < 0.12
  - http-api-data >= 0.4 && < 0.6
  - http-client >= 0.6 && < 0.8
  - http-client-tls >= 0.3 && < 0.4
  - http-media >= 0.8 && < 0.9
  - mime-mail >= 0.5 && < 0.6
  - monad-control >= 1 && < 1.1
  - monad-logger >= 0.3 && < 0.4
  - mtl >= 2.2 && < 2.3
  - servant >= 0.18 && < 0.20
  - servant-client >= 0.18 && < 0.20
  - text >= 1.2 && < 2.1
  - time >= 1.9 && < 1.13
  - transformers >= 0.5 && < 0.6
  - transformers-base >= 0.4 && < 0.5
  - unix-time >= 0.4 && < 0.5
  - unordered-containers >= 0.2 && < 0.3
  - wai >= 3.2 && < 3.3
  - wai-extra >= 3.1 && < 3.2
  - warp >= 3.3 && < 3.4

library:
  source-dirs:
    - src
  exposed-modules:
    - Google.Client
    - Google.Form
    - Google.JWT
    - Google.Response
    - Google.Type

github: arowM/haskell-google-server-api
